### PR TITLE
Added TS definitions

### PR DESCRIPTION
**Pull request by aaronbeall**
Initial attempt to address https://github.com/Kloudless/file-explorer/issues/89

Some open issues:

- Does not include Vue or React definitions.
- What is the "file metadata" returned in a "success" event? The docs didn't seem to spell this out, so I basically copied the shape of the object I saw in a test. Not clear what variants there are.
- I included the `destroy()` method for both Dropzone and Explorer, even though this isn't documented it was necessary in my use case to prevent problems after the user leaves the screen where the file-explorer was.
- I included the `update()` method on Dropzone, even though this isn't documented (I think it should be?)
- A few types are set ambiguously to `object`, like `oath(): object` and `translations: object` because it was not clear to me what the complete options for them are.

Tested this in my app and it worked for my purposes, but I'm only actually using `dropzone()` and a sub-set of options/events. I'm using React but not the actual React wrapper.

### CODE REVIEW

**Comment by vinodc** [comment]
@aaronbeall This is great! I appreciate you contributing your time towards these changes.

@ueewbd I know you've been looking into when we can add Typescript definitions. The open issues Aaron mentioned seem like a good starting point for when we have an opportunity to work on this item.

@aaronbeall To answer some of the questions:

* The file metadata in a success event is documented 1 to 2  levels deep on our [Storage API Docs](https://developers.kloudless.com/docs/v1/storage#files), but the exact attributes included depend on which storage service the file is from and some nested attributes like `raw.object` will likely just end up being `object`.
* Although update() and destroy() are used internally, it might make sense to document them for the reasons you've mentioned. We'll look into that.
* The expected format for the object returned by `oauth` includes attributes representing the [first leg query parameters](https://developers.kloudless.com/docs/v1/authentication#oauth-2.0-first-leg), other than `redirect_uri`, `state`, and `response_type`, and with alternate format for `extra_data`, `custom_properties`, and `raw`, as documented [here](https://github.com/Kloudless/authenticator#options).
* I'm not quite sure how to represent `translations`, but it would likely need to be a union type of some kind, since it accepts either a URL or the actual data. An example format for the data when it includes a single key, like `fr`, is [available here](https://github.com/Kloudless/file-explorer/blob/master/dev-server/static/translations-suite-sample.json). We know most of the known locales, but I believe it's possible to include arbitrary ones so we might end up having to allow for that ([SO suggestion](https://stackoverflow.com/a/44591688/827437)).

Thanks again for getting this ball rolling!

**Comment by aaronbeall** [comment]
Thanks for the clarifications! I'll make some updates.

> The file metadata in a success event is documented 1 to 2 levels deep on our [Storage API Docs](https://developers.kloudless.com/docs/v1/storage#files)

Exactly what I was looking for! Maybe a link to that in the `success(files)` docs would be nice?

> I'm not quite sure how to represent `translations`... We know most of the known locales, but I believe it's possible to include arbitrary ones so we might end up having to allow for that

Yeah, I debated whether to add a literal type for the known languages, but if users can add any language they want it ends up just being `string`. Same issue with file extensions and service names. I think I'll add the known languages and join with string like I did for those, and add the translation object.

**Comment by ueewbd** [comment]
Thanks for the contribution @aaronbeall !
We're reviewing your changes and making improvements if need.
We will let you know once we merge in.

**Comment by ueewbd** [comment]
Hi @aaronbeall ,

We've added TypeScript definitions for File Picker (previously named File Explorer).
We created an internal branch based on yours to work on and squashed yours into one commit: c620df8026c8d3514742510c21b7f52ed178ec01.
Therefore, GitHub cannot track the status of this PR. I made some changes here to resolve conflicts and will confirm merge although there are no changes.

**Pull request merged**
